/**
 * The battle bus' vocabulary: the names every event is emitted under,
 * the shapes they carry, and the map that pairs the two. Split by
 * what part of a fight each belongs to
 */

export { default as BattleEvents } from './names';
export { EffectType, MoveTargetType } from './shapes';
export type {
  CastingData,
  ChannelingData,
  EffectCause,
  MoveState,
  MoveTarget,
  ProgressData,
  TriggerMoveData,
} from './shapes';
export type {
  CheckUnitWeatherDurationEvent,
  TickEvent,
  UnitSetWeatherEvent,
  UnitWeatherEvent,
  WeatherEvent,
} from './weather';
export type {
  AllianceEvent,
  AllianceTeamEvent,
  CheckTeamStatusDurationEvent,
  CheckTeamStatusImmunityEvent,
  TeamEvent,
  TeamStatusEvent,
  TeamUnitEvent,
  TeamUpdateStatusEvent,
  TeamWeatherEvent,
} from './team';
export type {
  CheckUnitAttackEffectChanceEvent,
  CheckUnitAttackEffectEvent,
  CheckUnitCanCastEvent,
  CheckUnitCanChannelEvent,
  CheckUnitMoveAccuracyEvent,
  CheckUnitMoveContactEvent,
  CheckUnitMoveEvent,
  CheckUnitMoveHitsEvent,
  CheckUnitMoveImmunityEvent,
  CheckUnitMovePPEvent,
  CheckUnitMovePowerEvent,
  CheckUnitMovePriorityEvent,
  CheckUnitMoveStepsEvent,
  CheckUnitMoveTargetingEvent,
  CheckUnitMoveTimeEvent,
  CheckUnitMoveTypeEvent,
  CheckUnitRecoilEvent,
  CheckUnitTriggerMoveEvent,
  UnitAttackChildEvent,
  UnitAttackEvent,
  UnitAttackResolveAmountEvent,
  UnitAttackResolveCriticalEvent,
  UnitAttackResolveEffectivenessEvent,
  UnitAttackResolveStatEvent,
  UnitCastEvent,
  UnitChannelEvent,
  UnitMoveEvent,
  UnitMovePointsEvent,
  UnitTriggerMoveChildEvent,
  UnitTriggerMoveEvent,
  UnitTriggerMoveResolveAccuracyEvent,
  UnitTriggerMoveRollHitEvent,
  UnitTriggerMoveUpdateEvent,
  UnitUpdateCastEvent,
  UnitUpdateChannelEvent,
  UnitUpdateCooldownEvent,
} from './move';
export type {
  AIMoveChoice,
  CheckTeamAIUnitEvent,
  CheckUnitAIMoveScoreEvent,
  CheckUnitAIMoveUsableEvent,
  CheckUnitAIRatingEvent,
  UnitAIChooseMoveEvent,
} from './ai';
export type {
  CheckUnitAbilityEvent,
  CheckUnitCanConsumeItemEvent,
  CheckUnitCanDamageEvent,
  CheckUnitCanHealEvent,
  CheckUnitCanUpdateStageEvent,
  CheckUnitDrainEvent,
  CheckUnitEscapeEvent,
  CheckUnitGroundedEvent,
  CheckUnitItemEvent,
  CheckUnitItemThresholdEvent,
  CheckUnitStageEvent,
  CheckUnitStatEvent,
  CheckUnitStatusDurationEvent,
  CheckUnitStatusImmunityEvent,
  CheckUnitWeightEvent,
  UnitAbilityEvent,
  UnitCureEvent,
  UnitDamageEvent,
  UnitEntersFieldEvent,
  UnitEvent,
  UnitFaintsEvent,
  UnitHealEvent,
  UnitItemEvent,
  UnitRemoveItemEvent,
  UnitResetStagesEvent,
  UnitSetGenderEvent,
  UnitSetNatureEvent,
  UnitSetStatEvent,
  UnitSetValueEvent,
  UnitSpeciesEvent,
  UnitStageEvent,
  UnitStatEvent,
  UnitStatusEvent,
  UnitSwitchEvent,
  UnitTypeEvent,
  UnitUpdateStageEvent,
  UnitUpdateStatusEvent,
  UnitUpdateStatusTimerEvent,
  UnitUpdateSwitchEvent,
} from './unit';
export type { BattleEventMap } from './map';
